---
name: snapcast-server-libspot
version: dev
slug: snapcast-server-libspot
description: Host a Snapcast server with librespot
url: https://github.com/rwjack/addon-snapserver-spotify
codenotary: jack@cthd.icu
arch:
  - aarch64
  - amd64
  - armv7
  - i386
map: ["share:rw"]
audio: true
init: false
options:
  server_datadir: "/data/snapserver/"
  server_threads: -1
  spotify_stream: "stream = spotify:///librespot?name=Spotify"
  spotify_username: ""
  spotify_password: ""
  spotify_device_name: "HA_Snapcast"
  spotify_bitrate: 320
  spotify_volume: 100
  buffer: 1000
  codec: "flac"
  send_to_muted: "false"
  sampleformat: "48000:16:2"
  http_enabled: "true"
  http_doc_root: "/usr/share/snapserver/snapweb"
  tcp_enabled: "true"
  logging_enabled: "true"
schema:
  server_datadir: str?
  server_threads: int?
  spotify_stream: str?
  spotify_username: str
  spotify_password: password
  spotify_device_name: str
  spotify_bitrate: list(96|160|320)?
  spotify_volume: int?
  streams: str?
  stream_bis: str?
  stream_ter: str?
  buffer: int?
  codec: str?
  send_to_muted: str?
  sampleformat: str?
  http_enabled: str?
  http_doc_root: str?
  tcp_enabled: str?
  logging_enabled: str?
ports:
  1704/tcp: 1704
  1705/tcp: 1705
  1780/tcp: 1780
  #4953/tcp: 4953
ports_description:
  1704/tcp: Snapcast Stream
  1705/tcp: Snapcast JSON RPC
  1780/tcp: Snapcast HTTP controller
